### ISSUE TITLE
生产环境传webp会302

### ISSUE THREAD

**Issue by BingruLin** [eggjs/egg-multipart#65]
按照readme里面的写法，本地开发时都是好的，能传白名单里的各种图片或文件。

但是一旦部署之后，传webp以外的图片都会走到业务层，但传webp时会直接返回302到淘宝错误页。。。

![image](https://github.com/user-attachments/assets/2566be62-14af-430c-bb7f-1ee5001cbe0d)

我把egg-multipart复制了一个包，加了更详尽的日志，发现webp的情况下middware层就没触发。。。

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/aa76cb56-f568-44c9-b950-4a7ef179e201">

实在不知道怎么调试了，有没有大佬给点灵感

**Comment by fengmk2** [comment]
你的接入层是 aserver 吗？是被接入层拦截了。
